const {chromium}=require('playwright');const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const publicFiles=['index.html','editor.html','style.css','shell.css','core.js','app.js','editor.js','rubricas.js','privacidad.html','assets/bootstrap.min.css'];
const server=http.createServer((req,res)=>{const name=req.url==='/'?'index.html':req.url.slice(1);if(!publicFiles.includes(name)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',name.endsWith('.js')?'text/javascript; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,name)));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.CC_BROWSER?{executablePath:process.env.CC_BROWSER}:{})});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.log('BROWSER ERROR',m.text());});let gmailURL='';
 await context.route('https://mail.google.com/**',route=>{gmailURL=route.request().url();return route.abort();});
 await context.route('https://js.puter.com/v2/',route=>route.fulfill({contentType:'text/javascript',body:`window.sent=[];window.puter={auth:{signIn:async()=>{}},ai:{chat:async function*(prompt){window.sent.push(prompt);const records=JSON.parse(prompt.split('\\nRegistros: ')[1]);const out=records.slice().reverse().map(r=>({id:r.id,intro:'Texto de IA',competencias_evaluadas:r.competencias.map(c=>({nombre_competencia:c.competencia,rubrica:'Valoración de IA',recomendaciones:'Consejo personalizado de IA'})),conclusion:'Cierre de IA'}));yield {text:JSON.stringify(out)};}}};`}));
 await page.clock.install();await page.goto(`http://127.0.0.1:${server.address().port}`);const frame=page.frameLocator('#editor');
 assert.equal(await page.locator('#editor').getAttribute('sandbox'),'allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox');
 await page.locator('#connect').click();await page.getByText('Servicio cargado.',{exact:false}).waitFor();await page.locator('#connect').click();await page.getByText('Conectado.',{exact:false}).waitFor();
 assert.equal(await page.evaluate(()=>{try{document.querySelector('iframe').contentWindow.document.body;return false;}catch{return true;}}),true,'SDK cannot access identities DOM');
 await frame.locator('#data').fill('Nombre\tEmail\tInnovación\tTotal\nIDENTIDAD_SECRETA\tsecreto@example.es\t7,5\t9\nOTRA_PERSONA\totro@example.es\t4\t5');await frame.locator('button[type=submit]').click();await frame.locator('.result-text').first().waitFor();
 const prompt=(await page.evaluate(()=>sent))[0];assert.ok(!prompt.includes('IDENTIDAD_SECRETA'));assert.ok(!prompt.includes('secreto@example.es'));assert.ok(!prompt.includes('OTRA_PERSONA'));
 const first=frame.locator('article').first();assert.equal(await first.locator('h3').textContent(),'OTRA_PERSONA');assert.ok((await first.locator('textarea').inputValue()).includes('Consejo personalizado de IA'));assert.ok((await first.locator('textarea').inputValue()).includes('Calificación: 4'));
 assert.equal(await first.locator('button').isDisabled(),true);await first.locator('input[type=checkbox]').check();await first.locator('textarea').fill('Texto revisado');assert.equal(await first.locator('button').isDisabled(),true);await first.locator('input[type=checkbox]').check();const popup=context.waitForEvent('page');await first.locator('button').click();const p=await popup;await p.waitForLoadState().catch(()=>{});assert.equal(new URL(gmailURL).searchParams.get('to'),'otro@example.es');assert.equal(new URL(gmailURL).searchParams.get('body'),'Texto revisado');await p.close();
 await page.clock.fastForward(16*60*1000);assert.equal(await frame.locator('article').count(),0);
 await frame.locator('#data').fill('Nombre\tInnovación\n<img src=x onerror=alert(1)>\t8');await frame.locator('button[type=submit]').click();await frame.locator('.result-text').first().waitFor();assert.equal(await frame.locator('article img').count(),0);assert.ok(!((await page.evaluate(()=>sent))[1]).includes('<img'));
 const before=await page.evaluate(()=>sent.length);await frame.locator('#erase').click();await frame.locator('#data').fill('Nombre\tInnovación\tDiagnóstico\nA\t7\tprivado');await frame.locator('button[type=submit]').click();assert.equal(await page.evaluate(()=>sent.length),before);
 await frame.locator('#erase').click();await frame.locator('#data').fill('5 5 6 4 6 7\n6 5 4 3 4 5');await frame.locator('button[type=submit]').click();await frame.locator('.result-text').first().waitFor();assert.equal(await frame.locator('article').count(),2);assert.equal(await frame.locator('article h3').first().textContent(),'Alumno2');assert.ok((await frame.locator('article').first().textContent()).includes('alumno2@example.invalid'));assert.ok(!(await page.evaluate(()=>sent.at(-1))).includes('example.invalid'));
 if(process.env.CC_SCREENSHOTS){fs.mkdirSync(process.env.CC_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.CC_SCREENSHOTS,'ia-desktop.png'),fullPage:true});}
 await page.setViewportSize({width:390,height:844});assert.equal(await frame.locator('body').evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok(await frame.locator('.result-text').first().evaluate(e=>e.getBoundingClientRect().height>=300));if(process.env.CC_SCREENSHOTS)await page.screenshot({path:path.join(process.env.CC_SCREENSHOTS,'ia-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('Browser passed with mocked provider: isolated identity DOM, no identifiers in prompt, AI recommendations, shuffled identity mapping, review, Gmail, idle erasure, XSS text, rejection before sending. No real AI calls.');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

