const {test}=require('node:test');const assert=require('node:assert/strict');
const F=require('../core.js');const R=require('../rubricas.js');
const source='Nombre\tEmail\tCompetency 1 Level\tComunicación oral\tTotal\nNombreSecreto\tsecreto@example.es\t7,25\tNivel 3\t9';
function reply(records){return records.map(r=>({id:r.id,intro:'Introducción',competencias_evaluadas:r.competencias.map(c=>({nombre_competencia:c.competencia,rubrica:'Valoración',recomendaciones:'Recomendación personalizada'})),conclusion:'Conclusión'}));}
test('separates identities and final mark; canonicalizes headers and grades',()=>{const a=F.prepare(F.parseStudents(source)),b=F.prepare(F.parseStudents(source));const prompt=F.prompt(a.records,R);for(const secret of ['NombreSecreto','secreto@example.es','Total','7,25'])assert.ok(!prompt.includes(secret));assert.equal(a.identities.get(a.records[0].id).total,9);assert.equal(a.records[0].competencias[0].valor,7.25);assert.notEqual(a.records[0].id,b.records[0].id);});
test('rejects unexpected/free-text columns and nonnumeric notes before sending',()=>{for(const s of [source.replace('Total','Diagnóstico'),source.replace('7,25','secreto@example.es'),source.replace('7,25','11'),source.replace('7,25','7.251'),source.replace('Nombre\tEmail','Nombre\tNombre')])assert.throws(()=>F.parseStudents(s));});
test('rejects malformed rows, email injection, duplicates and oversize',()=>{for(const s of [source+'\textra',source.replace('secreto@example.es','x@a.es&bcc=y@a.es'),source+'\nNombre2\tsecreto@example.es\t3\tNivel 1\t5','x'.repeat(100001)])assert.throws(()=>F.parseStudents(s));});
test('validates quoted spreadsheet fields',()=>{assert.deepEqual(F.parseTSV('"a\tb"\t"c""d"\r\n'),[['a\tb','c"d']]);assert.throws(()=>F.parseTSV('"unfinished'));});
test('bridge reconstructs allowlisted payload ignoring injected private fields',()=>{const {records}=F.prepare(F.parseStudents(source));records[0].name='PRIVATE';records[0].email='PRIVATE';records[0].competencias[0].extra='PRIVATE';assert.ok(!F.prompt(records,R).includes('PRIVATE'));records[0].competencias[0].competencia='PRIVATE';assert.throws(()=>F.prompt(records,R));});
test('correlates shuffled responses using random ids, never order',()=>{const {records}=F.prepare(F.parseStudents(source+'\nOtro\totro@example.es\t4\tNivel 2\t4'));const r=reply(records).reverse();assert.equal(F.response(JSON.stringify(r),records)[0].id,records[1].id);});
test('rejects missing, unknown or repeated identities and altered competencies',()=>{const {records}=F.prepare(F.parseStudents(source));for(const response of [[],[{...reply(records)[0],id:'unknown'}],[{...reply(records)[0],competencias_evaluadas:[]}],reply(records).concat(reply(records))])assert.throws(()=>F.response(JSON.stringify(response),records));});
test('strips invented identity, notes and unrequested extra fields from response',()=>{const {records}=F.prepare(F.parseStudents(source));const r=reply(records);r[0].email='invented';r[0].competencias_evaluadas[0].nota=0;assert.ok(!JSON.stringify(F.response(JSON.stringify(r),records)).includes('invented'));assert.equal(F.response(JSON.stringify(r),records)[0].competencias_evaluadas[0].nota,undefined);});
